remote_theme: jekyll/minima@d4d779a
title: Tallinn Real Estate Blog â€“ Market News, Prices & Trends in Estonia
description: Stay updated with the latest real estate news in Tallinn and Estonia. Explore housing prices, rental demand, investment opportunities, and expert property market insights.
minima:
  skin: auto
#  nav_pages:
#      - about.md
#      - portfolio.md
  date_format: "%d.%m.%Y %H:%M"
  show_excerpts: false
  hide_site_feed_link: true